version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: my-backend
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: pass123
      DB_NAME: testdb
    expose:               # expose only inside Docker network
      - "5000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: my-frontend
    restart: unless-stopped
    expose:               # expose only inside Docker network
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
